# Introduction to TensorFlow

In [ ]:
# Import TensrFlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# Craeate tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimension of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of the vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the dimension of the matrix
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8., 9.]], dtype = tf.float16)# Specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                            [4,5,6],
                             [7,8,9]],
                            [[10,11,12],
                             [13,14,15],
                             [16,17,18]]])
tensor 

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of ndim
* Tensor: an n-dimensional array of numbers (When n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creatinfg tensors with tf.variable

In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])# tf.Variable is changeable as it's name Variable
unchangeable_tensor = tf.constant([10, 7])# tf.constant is unchangeable as it is constant
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Try to change the elements in changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# What if we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try to change the elements in the unchagebale tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating Random tensors
Random tensor are tensors of some arbitrary size which conrain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducability
random_1 = random_1.normal(shape= (3,2))
random_1
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3,2))

# Are they equal?
random_1, random_2, random_1 ==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling the order of elements of tensors 

In [ ]:
# shuffle a tensor (valuabel for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle( not_shuffled, seed =42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Exercise:** Read through TensorFlow documentation on random seed generator
https://www.tensorflow.org/api_docs/python/tf/random/set_seed adn practice writing 5 random tensors and shuffle them

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
shuffled = tf.constant([[[1,4],
                         [16,9],
                         [12,36]],
                        [[18,24],
                         [34,38],
                         [26,28]]])
# Check the dimensions of the random tensors
shuffled.ndim, shuffled

(3, <tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
 array([[[ 1,  4],
         [16,  9],
         [12, 36]],
 
        [[18, 24],
         [34, 38],
         [26, 28]]], dtype=int32)>)

In [ ]:
tf.random.shuffle(shuffled)

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[18, 24],
        [34, 38],
        [26, 28]],

       [[ 1,  4],
        [16,  9],
        [12, 36]]], dtype=int32)>

In [ ]:
# Another tensor random
tensor1 = tf.constant([[[4,6],
                       [8,24]],
                       [[28,12],
                        [16,32]],
                       [[26,36],
                        [18,38]]], dtype=tf.int16)
tensor1.ndim, tensor1

(3, <tf.Tensor: shape=(3, 2, 2), dtype=int16, numpy=
 array([[[ 4,  6],
         [ 8, 24]],
 
        [[28, 12],
         [16, 32]],
 
        [[26, 36],
         [18, 38]]], dtype=int16)>)

In [ ]:
tf.random.set_seed(1)
tf.random.shuffle(tensor1, seed=1)

<tf.Tensor: shape=(3, 2, 2), dtype=int16, numpy=
array([[[ 4,  6],
        [ 8, 24]],

       [[28, 12],
        [16, 32]],

       [[26, 36],
        [18, 38]]], dtype=int16)>

In [ ]:
tensor2 = tf.constant([[1,2],
                       [3,4],
                       [4,5]], dtype = tf.int8)
tensor2.ndim
tensor2

<tf.Tensor: shape=(3, 2), dtype=int8, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]], dtype=int8)>

### Creating tensors with other ways

In [ ]:
# Create a tensor of all ones
tf.ones([10,10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tenosr of all zeros
tf.zeros(shape=(5,6))

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors
>The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU(Much faster for Numerical computing).

In [ ]:
# You can also turn Numpy arrays in tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Create a Numpy array between 1 and 25
numpy_A
# A = tf.constant(some_matrix) # Capital for matrix or tensors
# a = tf.constant(vector) # non-capital for vctor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# Convert numpy array into tensor
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
# Let's create tensor of 3 dimension fro numpy array
A =tf.constant(numpy_A, shape = (2,3,4)) # Here we have to be careful about the nmber of the elements. As we have created numpy array in the range of 1 to 25 to 24 elements
A,numpy_A,A.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 3)

In [ ]:
# What if we use in shape more elements than the range of our array
#A = tf.contant(numpy_A, shape=(2,5,4))# Throws an error because shape is out of range
A = tf.constant(numpy_A, shape=(8,3))
A

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape = (3,2,4))
A, A.ndim

(<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>, 3)

### Getting information from Tensors
* Shape
* Rank(Dimensions)
* Axis or dimension
* Size

In [ ]:
# Let's create a rank 4 tensor
rank_4_tensor = tf.ones(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
#Let's Try to create rank 5 tensor
rank_5_tensor = tf.zeros(shape=(1,2,3,4,5))
rank_5_tensor

<tf.Tensor: shape=(1, 2, 3, 4, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [ ]:
print("The DataType of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank) is:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))# To show with he tf.tensor and the shape of the tnesor
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

The DataType of every element: <dtype: 'float32'>
Number of dimensions (rank) is: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing Tensors
Tensors can be indexed just like Python list

In [ ]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
some_list, some_list[-1] 

([1, 2, 3, 4], 4)

In [ ]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis= -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis =0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
# Again using tf.newaxis in rank_3 tensor
rank_4_tensor_axis = rank_3_tensor[..., tf.newaxis]
rank_4_tensor_axis, rank_4_tensor_axis.ndim

(<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
 array([[[[10]],
 
         [[ 7]]],
 
 
        [[[ 3]],
 
         [[ 4]]]], dtype=int32)>, 4)

In [ ]:
# Using tf.expand_dims() to expand at axis = 1
tf.expand_dims(rank_2_tensor, axis = 1)


<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating Tensors
**Basic Operations**
* +, -, /, *

In [ ]:
# YOu can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tenosr is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# But the original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too
tensor = tf.multiply(tensor, 10)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Here the Original tensor is changed
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**
* Using builtin methods of tensorflow for multiplication and addition is faster than the matrix manipulation using operators

In [ ]:
# Defining a tensor X
X = tf.constant([[1,2,3],[4,5,6]])
X, X.dtype

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>, tf.int32)

In [ ]:
# Defining a tensor Y
Y = tf.constant([[4,5,6],[7,8,9]])
Y, Y.shape

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 5, 6],
        [7, 8, 9]], dtype=int32)>, TensorShape([2, 3]))

In [ ]:
# Multiplying(Dot product of tensor using tf.matmul)
tf.matmul(X, tf.reshape(Y, shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 40,  46],
       [ 94, 109]], dtype=int32)>

In [ ]:
# Transposing the tensor
C = tf.transpose(Y)
C, C.shape

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 7],
        [5, 8],
        [6, 9]], dtype=int32)>, TensorShape([3, 2]))

In [ ]:
# Taking dot product of the tensors using tf.tensordot
tf.tensordot(X, tf.transpose(Y), axes =0), # axes 0 means the outer product of the tensors
tf.tensordot(X, tf.transpose(Y), axes = 1)# axes = 1 means the matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 32,  50],
       [ 77, 122]], dtype=int32)>

In [ ]:
# Addition of tensors using tf.add (built in function of tensorflow)
tf.add(X, Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  7,  9],
       [11, 13, 15]], dtype=int32)>

In [ ]:
X.dtype, Y.dtype

(tf.int32, tf.int32)

### Changing the Datatypes of the tensors
* tf.cast( )is used 

In [ ]:
# Original tensors with original dtypes
X,X.dtype,Y,Y.dtype

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 tf.int32,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 tf.int32)

In [ ]:
# Changing the Datatype of the tensor from int32 to int16
tf.cast(X, dtype= tf.int16)

<tf.Tensor: shape=(2, 3), dtype=int16, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)>

In [ ]:
# Changing the Datatype of Y from int32 to float16
tf.cast(Y, dtype = tf.float16)

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

### Aggregating tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D) # Absolute value is always without -ve sign

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random ensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 3, 10, 37,  2, 30, 88,  6, 55, 95, 55, 42, 87, 88,  2, 84, 74, 21,
       54,  6, 61,  0, 97,  3, 21, 62, 11, 10, 64, 25,  4, 30, 63,  0, 41,
       79, 85, 16, 37, 88, 97, 39, 70, 10, 16, 54, 81, 43,  5, 10, 16])>

In [ ]:
tf.random.shuffle(E)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([88,  6, 88, 95,  2, 97, 62, 88, 16,  3, 43, 84,  3, 63, 54, 10, 10,
       41, 37,  4, 16, 85, 25, 16, 54,  0, 55, 39, 64,  5, 10, 30, 21, 21,
       74,  2, 11,  0, 70, 61, 37, 97, 55, 87, 30,  6, 42, 81, 79, 10])>

In [ ]:
# Find the Minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=41>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2077>

In [ ]:
# Find the Variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16)) # Here we get the error because the data is in integer form

<tf.Tensor: shape=(), dtype=float16, numpy=1033.0>

In [ ]:
# Find the variance
E = tf.cast(E, dtype = tf.float16) # Changing the data type of the tensor to get variance and standard deviation
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float16, numpy=1033.0>

In [ ]:
# Find the standard Deviation
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float16, numpy=32.12>

**Let's Import tensorflow Probability for statistics functions**

In [ ]:
# Import tensorflow statistics
import tensorflow_probability as tfp
tfp.stats.variance(E) # Finding the variance using the probability methods

<tf.Tensor: shape=(), dtype=float16, numpy=1033.0>

In [ ]:
# Find the standard deviation of the tensor using probablity stats
tfp.stats.stddev(E)

<tf.Tensor: shape=(), dtype=float16, numpy=32.12>

### Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F  = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[(tf.argmax(F))]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the maximum value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# We have done this using normal distribution
tf.random.set_seed(43)
G = tf.random.normal(shape =[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([-0.02050048, -1.6105652 , -0.72483575, -0.5450064 ,  1.0539695 ,
       -0.89128387,  0.09752923, -1.1036574 ,  0.47783953,  0.18255234,
       -0.23718892,  0.3108687 ,  0.15652822, -0.88578725, -1.1723399 ,
        1.2841821 ,  1.248613  , -1.2372903 , -0.8686831 , -0.4494087 ,
        0.4442081 ,  1.4079124 , -1.3365219 ,  3.2284563 , -1.9076515 ,
        0.17897356,  0.08237004, -1.0684288 ,  1.2464011 , -0.39724466,
       -0.5205348 , -0.2745581 ,  1.9562446 , -3.0211666 ,  0.36173433,
        0.15002829, -0.03679373,  1.0056065 ,  1.2866769 , -0.24367902,
       -0.32192045,  0.11693916, -0.97043836, -2.1374395 , -0.10489912,
        1.6242274 ,  0.72912854,  0.8255518 , -1.0467843 , -0.38750738],
      dtype=float32)>

In [ ]:
# Finding the maximum value of the tesnor
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=3.2284563>

In [ ]:
# Find the positional maximum of the tensor
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=23>

In [ ]:
# Index to the maximum value of tensor
G[(tf.argmax(G))]

<tf.Tensor: shape=(), dtype=float32, numpy=3.2284563>

In [ ]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the position of minimum value of tensor
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Indexing to the minimum value
# Finding the minimum value(tf.reduce_min())
F[(tf.argmin(F))], tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing tensor
(Removing all 1-dimesnions in the tensor)

In [ ]:
# Create another tensor with multiple 1-dimensions in tensor
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape = [50]), shape=(1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
# Squeezing tensor (Removing all extra 1-dimensions from tensor)
H_squeezed = tf.squeeze(H)
H_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

###One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green, blue, purple

# one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth = 4, on_value="Yo man I love deep learning", off_value="I also like to play cricket")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo man I love deep learning', b'I also like to play cricket',
        b'I also like to play cricket', b'I also like to play cricket'],
       [b'I also like to play cricket', b'Yo man I love deep learning',
        b'I also like to play cricket', b'I also like to play cricket'],
       [b'I also like to play cricket', b'I also like to play cricket',
        b'Yo man I love deep learning', b'I also like to play cricket'],
       [b'I also like to play cricket', b'I also like to play cricket',
        b'I also like to play cricket', b'Yo man I love deep learning']],
      dtype=object)>

In [ ]:
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
t = tf.one_hot(some_list, depth=4, on_value=24, off_value=48)
t
t = tf.cast(t, dtype=tf.int16)
t

<tf.Tensor: shape=(4, 4), dtype=int16, numpy=
array([[24, 48, 48, 48],
       [48, 24, 48, 48],
       [48, 48, 24, 48],
       [48, 48, 48, 24]], dtype=int16)>

### Squaring, log, square, root

In [ ]:
# Create a new tensor
I = tf.range(1, 10)
I

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the squareroot
#tf.sqrt(I)# It throws error as it the value is not in float
tf.sqrt(tf.cast(I, dtype = tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
# Find the log
tf.math.log(tf.cast(I, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

Practice some of the math functions in tf.math in tensorflow

### Tensors and Numpy Compatibility
TensorFlow interacts beautifully with NumPy arrays

In [ ]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert our tesor back to a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# The default types of ech are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

Numpy: Numpy is  The fundamental Package of scientific computing with Python

**Difference:** The main difference between Numpy and TensorFlow is that a **TensorFlow tesor** can be run on a GPU or **TPU**
(for faster numerical processing)

### Finding access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Jan 24 16:18:30 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P8    33W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note** If you have access to CUDA-enabled GPU, TensorFlow will auromatically use it whenever possible