In [1]:
# import Tensorflow
import tensorflow as tf

In [5]:
# Create a vector
vector = tf.constant([5])
vector.dtype,vector.ndim,
vector

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5], dtype=int32)>

In [3]:
# Finding access to GPU
!nvidia-smi


Tue Jan 25 15:24:00 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    58W / 149W |    147MiB / 11441MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
# Finding the physical devices connected to the system
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [7]:
# Create a scalar
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [8]:
# Creating a tensor
matrix = tf.constant([[1,2],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [17]:
# Find the shape, rank, size and datatype of the tensor
print("Shape of the tensor: ", tensor.shape)
print("Size of the tensor: ", tf.size(tensor).numpy())
print("Datatype of the tensor: " ,tensor.dtype)
print("Dimensions of the tensor(rank): ",tensor.ndim)

Shape of the tensor:  (2, 2, 3)
Size of the tensor:  12
Datatype of the tensor:  <dtype: 'int32'>
Dimensions of the tensor(rank):  3


In [24]:
# Create 1st tensor
tensor_0 = tf.zeros([5, 300])
tensor_0

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [23]:
tensor_1 = tf.ones([5, 300])
tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>

In [25]:
tensor_0 * tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [27]:
tf.tensordot(tensor_0, tensor_1, axes =1)

InvalidArgumentError: ignored

In [31]:
# Finding dot product of the tesors
tf.tensordot(tensor_0, tf.reshape(tensor_1, shape = [300, 5]), axes= 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [69]:
# Create a tensor with random values between 0 and 1
tensor_2 = tf.random.uniform(shape = [224, 224, 3], minval = 0, maxval = 1)
# tensor_2 = tf.constant(np.random.randint(0, 1 , size = 100) )# This is for size
tensor_2

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.20865393, 0.26914918, 0.48286211],
        [0.97293997, 0.37753153, 0.7522633 ],
        [0.6924995 , 0.00649309, 0.9992529 ],
        ...,
        [0.9622246 , 0.03652263, 0.18243384],
        [0.8865051 , 0.76359737, 0.6688559 ],
        [0.30279946, 0.82591236, 0.07347882]],

       [[0.41297543, 0.5775207 , 0.26347196],
        [0.2983588 , 0.10833788, 0.7710283 ],
        [0.6795379 , 0.9837111 , 0.85753953],
        ...,
        [0.8545263 , 0.18130851, 0.1655215 ],
        [0.0942359 , 0.61538815, 0.6569351 ],
        [0.5794661 , 0.9452139 , 0.4552127 ]],

       [[0.18736029, 0.4845711 , 0.98327374],
        [0.5569376 , 0.88873816, 0.99412906],
        [0.9980439 , 0.8430779 , 0.4396212 ],
        ...,
        [0.09349334, 0.6930281 , 0.29120052],
        [0.25896633, 0.00743937, 0.20597064],
        [0.4467814 , 0.19911814, 0.2534324 ]],

       ...,

       [[0.9309385 , 0.9620106 , 0.2944609 ],
        [0.39

In [36]:
# Find the maximum value of the tensor
tf.reduce_max(tensor_2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999917>

In [38]:
# Find the minimum value of the tensor
tf.reduce_min(tensor_2)

<tf.Tensor: shape=(), dtype=float32, numpy=2.1457672e-06>

In [44]:
#import tensorflow_probability as tfp
#tf.argmax(tensor_2)

In [46]:
# Create a tensor with random values of shape [1, 224, 224, 3]
tensor_3 = tf.random.uniform(shape =[1, 224, 224, 3])
tensor_3

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.12572014, 0.81223536, 0.80964994],
         [0.03556085, 0.29596913, 0.5258739 ],
         [0.15387523, 0.98248684, 0.7566776 ],
         ...,
         [0.6585183 , 0.01920521, 0.66237974],
         [0.06506324, 0.11039066, 0.06626797],
         [0.49731433, 0.74514866, 0.10491729]],

        [[0.6999123 , 0.88158154, 0.49509513],
         [0.05415797, 0.44081974, 0.9354367 ],
         [0.98771405, 0.6966516 , 0.07593739],
         ...,
         [0.19782293, 0.80823684, 0.610064  ],
         [0.13156569, 0.35167944, 0.92952406],
         [0.07905793, 0.3435793 , 0.8376055 ]],

        [[0.20179105, 0.6599388 , 0.98492813],
         [0.1893822 , 0.29174435, 0.4812405 ],
         [0.7935215 , 0.7522532 , 0.08701718],
         ...,
         [0.10887516, 0.041417  , 0.9422631 ],
         [0.41648042, 0.87478805, 0.1864096 ],
         [0.16446173, 0.24263608, 0.29647136]],

        ...,

        [[0.47886372, 0.24748445, 

In [48]:
# Squeezing the tensor (tensor_3)
squeezing = tf.squeeze(tensor_3)
squeezing.shape

TensorShape([224, 224, 3])

In [49]:
# Creating another matrix
tensor_4 = tf.random.uniform(shape= [224, 224, 3])
tensor_4.shape

TensorShape([224, 224, 3])

In [57]:
# Squeezing the tensor_4
tensor_4 = tf.squeeze(tensor_4)
# expanding the dimensions of tensor_4 with tf.expand_dims at index=0
tensor_4 = tf.expand_dims(tensor_4, 0)
tensor_4.shape

TensorShape([1, 224, 224, 3])

In [76]:
# Create a tensor of own choices of shape = [10]
tensor_5 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tensor_5

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [77]:
# Finding the index of the maximum value in tensor_5
tf.argmax(tensor_5)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [78]:
# Checking that the index's max value is equal or not to the max value
tensor_5[tf.argmax(tensor_5)]== tf.reduce_max(tensor_5)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [79]:
# Finding the positional maximum value of the tensor_5
tensor_5[tf.argmax(tensor_5)]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [82]:
# Using one_hot encoding to encode values of the tensor
tensor_6 = tf.one_hot(tensor_5 , on_value = "hello", off_value = "hi", depth = 10 )

In [83]:
tensor_6

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'hi', b'hello', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi',
        b'hi'],
       [b'hi', b'hi', b'hello', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi',
        b'hi'],
       [b'hi', b'hi', b'hi', b'hello', b'hi', b'hi', b'hi', b'hi', b'hi',
        b'hi'],
       [b'hi', b'hi', b'hi', b'hi', b'hello', b'hi', b'hi', b'hi', b'hi',
        b'hi'],
       [b'hi', b'hi', b'hi', b'hi', b'hi', b'hello', b'hi', b'hi', b'hi',
        b'hi'],
       [b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hello', b'hi', b'hi',
        b'hi'],
       [b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hello', b'hi',
        b'hi'],
       [b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hello',
        b'hi'],
       [b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi',
        b'hello'],
       [b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi', b'hi',
        b'hi']], dtype=object)>