In [ ]:
import numpy as np

# DataTypes & Attributes

In [ ]:
# Numpy's main datatype is ndarray
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [ ]:
type(a1) 
a1.shape

(3,)

In [ ]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [ ]:
a2
type(a2)
a2.shape

(2, 3)

In [ ]:
# Creating another array
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [ ]:
a3.ndim
#a3.shape


3

In [ ]:
# To check the dimension of the array ndim is used
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [ ]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [ ]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [ ]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
import pandas as pd

In [ ]:
# Creating Datafram from numpy array
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# Creating Arrays

In [ ]:
# Creating array containing only 1s
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ones = np.ones((4,5))

In [ ]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
type(ones), type(zeros)

(numpy.ndarray, numpy.ndarray)

In [ ]:
ones.shape

(4, 5)

In [ ]:
range_array = np.arange(0, 11, 2)
range_array

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[7, 9, 5, 4, 5],
       [6, 6, 3, 1, 1],
       [2, 3, 0, 9, 8]])

In [ ]:
random_array.shape

(3, 5)

In [ ]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.89803142, 0.61723839, 0.565707  ],
       [0.26609155, 0.25804362, 0.85112693],
       [0.7818674 , 0.49748235, 0.83231682],
       [0.34776287, 0.05872397, 0.86951476],
       [0.76820488, 0.93335502, 0.60114166]])

In [ ]:
random_array_2.shape

(5, 3)

In [ ]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.14846035, 0.66907855, 0.0840504 ],
       [0.60455393, 0.05962036, 0.5504059 ],
       [0.83211472, 0.15555223, 0.84905097],
       [0.1999367 , 0.18217607, 0.3787589 ],
       [0.78111816, 0.63206931, 0.29099636]])

In [ ]:
random_array_4 = np.random.random((8,3))

In [ ]:
random_array_4

array([[0.86510015, 0.15637264, 0.45607317],
       [0.76319509, 0.25832536, 0.17962674],
       [0.50267092, 0.29179636, 0.450754  ],
       [0.94655248, 0.85804129, 0.13259252],
       [0.5185966 , 0.60890069, 0.14550515],
       [0.61802149, 0.40386313, 0.98076842],
       [0.67025205, 0.8308624 , 0.05410851],
       [0.45612671, 0.41525378, 0.04394859]])

In [ ]:
random_array_5 = np.random.random((4,5,6))
random_array_5

array([[[0.17656038, 0.82769185, 0.28165584, 0.81448031, 0.27339751,
         0.85288595],
        [0.62362833, 0.76891982, 0.57890935, 0.17982362, 0.64178554,
         0.49850032],
        [0.59982913, 0.96750591, 0.75059275, 0.01419535, 0.25828   ,
         0.07324713],
        [0.42482162, 0.86279444, 0.91186649, 0.37373476, 0.35332836,
         0.90497312],
        [0.00745563, 0.73875998, 0.00437487, 0.4852494 , 0.06162357,
         0.54838948]],

       [[0.68411557, 0.35030699, 0.22000009, 0.73442046, 0.17557052,
         0.81526189],
        [0.63051091, 0.18391104, 0.73880104, 0.72509532, 0.32577337,
         0.0561609 ],
        [0.69572075, 0.70887128, 0.75668224, 0.54138718, 0.32734136,
         0.02873189],
        [0.95474457, 0.19332232, 0.95767289, 0.62942082, 0.0510375 ,
         0.76744353],
        [0.34613915, 0.60823142, 0.5751631 , 0.39720302, 0.31710244,
         0.28624827]],

       [[0.61698589, 0.81323209, 0.1361533 , 0.03760961, 0.15888618,
         0.079487

In [ ]:
random_array_6 = np.random.randint(0, 100, size =(4,5,6))
random_array_6

array([[[37,  2,  1, 51, 43, 77],
        [30, 12,  1, 11, 18,  3],
        [89, 65, 60, 13, 55, 34],
        [73, 48, 79, 38, 10, 82],
        [73, 82, 78, 91, 48, 67]],

       [[ 4, 23, 86, 61, 78, 56],
        [94,  9, 81, 73, 33, 45],
        [55, 10, 51, 67, 71, 81],
        [23, 29, 85, 61, 64, 54],
        [84, 19,  8, 80, 44, 18]],

       [[91, 17, 58, 13, 43, 66],
        [40, 86, 68, 51, 41, 93],
        [ 8, 11, 73, 79,  5, 59],
        [71, 80, 95, 86, 12, 61],
        [97, 95, 68, 26, 56, 47]],

       [[67, 16, 82, 25, 93, 84],
        [65, 40, 64, 47, 14, 80],
        [93,  3, 33, 85, 41, 61],
        [26, 51, 39, 11, 54, 17],
        [94, 23, 99, 87, 66, 31]]])

In [ ]:
np.shape(random_array_6), type(random_array_6)

((4, 5, 6), numpy.ndarray)

In [ ]:
random_array_6.T.shape

(6, 5, 4)

# Dot Product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size =(5,3))
mat2 = np.random.randint(10, size =(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [ ]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [ ]:
# Element wise matrix multiplication (Hardmard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [ ]:
# Dot Porduct
np.dot(mat1, mat2)
mat1.T.shape

ValueError: ignored

In [ ]:
mat2.T.shape

(3, 5)

In [ ]:
# For dot product number of columns of 1st matrix should be equal to the number of rows of 2nd
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# Dot prodeuct example(nut butter sales)

In [ ]:
np.random.seed(0)
#Number of jars sold
sales_amounts = np.random.randint(20, size= (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [ ]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns = ["Almond butter", "Peanut butter", "Cachew butter"])
weekly_sales

Almond butter  Peanut butter  Cachew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
#Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [ ]:
#Create butter _prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index = ["Price"],
                             columns = ["Almond butter", "Peanut butter", "Cachew butter"])

In [ ]:
butter_prices

Almond butter  Peanut butter  Cachew butter
Price             10              8             12

In [ ]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [ ]:
# Create daily sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [ ]:
# Doesn't work not the right shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: ignored

In [ ]:
weekly_sales["Total ($)"]= daily_sales.T
weekly_sales

# Practice

In [ ]:
sales_quantity = np.random.randint(20, size =(5,3))
sales_quantity

array([[14, 17,  5],
       [13,  8,  9],
       [19, 16, 19],
       [ 5, 15, 15],
       [ 0, 18,  3]])

In [ ]:
weekly_sale = pd.DataFrame(sales_quantity,
                           index = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
                           columns = ["Ps4", "Xbox", "Nintendo"])
weekly_sale

Ps4  Xbox  Nintendo
Monday      14    17         5
Tuesday     13     8         9
Wednesday   19    16        19
Thursday     5    15        15
Friday       0    18         3

In [ ]:
price = np.array([1000, 800, 700])
price

array([1000,  800,  700])

In [ ]:
console_price = pd.DataFrame(price.reshape(1,3),
                             index = ["Price"],
                             columns = ["Ps4", "Xbox", "Nintendo"])
console_price

Ps4  Xbox  Nintendo
Price  1000   800       700

In [ ]:
daily_sale = np.dot(weekly_sale, price)

In [ ]:
daily_sale

array([31100, 25700, 45100, 27500, 16500])

In [ ]:
price

array([1000,  800,  700])

In [ ]:
daily_sale = console_price.dot(weekly_sale.T)
daily_sale

Monday  Tuesday  Wednesday  Thursday  Friday
Price   31100    25700      45100     27500   16500

In [ ]:
weekly_sale["Total ($)"] = daily_sale.T

In [ ]:
weekly_sale 

Ps4  Xbox  Nintendo  Total ($)
Monday      14    17         5      31100
Tuesday     13     8         9      25700
Wednesday   19    16        19      45100
Thursday     5    15        15      27500
Friday       0    18         3      16500

# Comparison Operators

In [ ]:
a1, a2

(array([1, 2, 3]), array([[1, 2, 3],
        [4, 5, 6]]))

In [ ]:
a2>a1

array([[False, False, False],
       [ True,  True,  True]])

In [ ]:
a1 == a1

array([ True,  True,  True])

In [ ]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
bool_array = a1<a2
bool_array

array([[False, False, False],
       [ True,  True,  True]])

In [ ]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

# Sorting Array

In [ ]:
random_array = np.random.randint(10, size = (3,5))
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [ ]:
# Sorting
np.sort(random_array)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [ ]:
# Sorting the index values
np.argsort(random_array)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]])

In [2]:
<img src = "/content/drive/MyDrive/Numpy-images/panda.png"/>

SyntaxError: ignored

In [3]:
from matplotlib.image import imread
panda = imread("/content/drive/MyDrive/Numpy-images/panda.png")

In [4]:
print(type(panda))

<class 'numpy.ndarray'>


In [ ]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [ ]:
panda.dtype

dtype('float32')

In [ ]:
panda.shape

(2330, 3500, 3)

In [ ]:
panda[:1]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [ ]:
ar1 = np.array([[[1,2,3],
                  [4,5,6]],
                 [[7,8,9],
                 [10,11,12]],
                 [[13,14,15],
                 [16,17,18]],
                [[19,20,21],
                [22,23,24]]])

In [ ]:
ar1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [ ]:
ar1.shape

(4, 2, 3)

In [ ]:
ar2 =np.array([[[5,6,7],
              [8,9,10]],
              [[11,12,13],
               [14,15,16]]])

In [ ]:
ar2

array([[[ 5,  6,  7],
        [ 8,  9, 10]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [ ]:
ar2.shape

(2, 2, 3)

In [ ]:
ar2.dtype

dtype('int64')

In [ ]:
type(ar2)

numpy.ndarray

In [ ]:
ar5 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [ ]:
ar5.shape

(2, 3, 3)

In [ ]:
ar3 = np.array([[1,2,3],
               [4,5,6]])

In [ ]:
ar3.shape

(2, 3)

In [ ]:
ar3*ar5

ValueError: ignored

In [ ]:
ar5.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [ ]:
ar5.T.shape

(3, 3, 2)

In [ ]:
ar3*ar5.T

ValueError: ignored

In [ ]:
ar5.reshape(3,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
ar5

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
ar3*ar5.reshape(3,2,3)

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

In [5]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [6]:
tensor1 = tf.constant(panda)

In [8]:
tensor1

<tf.Tensor: shape=(2330, 3500, 3), dtype=float32, numpy=
array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.

In [9]:
tensor1.dtype

tf.float32

In [10]:
tensor1.shape

TensorShape([2330, 3500, 3])