### Intro to tensors

In [1]:
# Import tensorflow
import tensorflow as tf

In [2]:
# Create a tensor with tf.constant
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [3]:
# Create a vector
vector = tf.constant([1,2,3,4,5])
vector

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [4]:
# Checking the dimension of the vector using ndim
vector.ndim

1

In [5]:
# Now let's create a matrix
matrix = tf.constant([[1,2,3,4],
                      [5,6,7,8]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [6]:
# Checking the dimension of the matrix
matrix.ndim

2

In [7]:
# Let's Create another matrix with another way like
matrix_1 = tf.constant([[[1,5,7,4],
                        [3,8,9,7]],
                        [[0,4,3,9],
                       [12,34,65,9]],
                        [[45,76,89,78],
                        [45,56,78,66]]])
matrix_1, matrix_1.ndim

(<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
 array([[[ 1,  5,  7,  4],
         [ 3,  8,  9,  7]],
 
        [[ 0,  4,  3,  9],
         [12, 34, 65,  9]],
 
        [[45, 76, 89, 78],
         [45, 56, 78, 66]]], dtype=int32)>, 3)

In [8]:
# Let's Create another tensor
tensor = tf.constant([[[23,24,25],
                      [12,13,14]],
                      [[15,16,17],
                       [18,19,20]],
                      [[21,22,27],
                       [30,31,32]]], dtype = tf.int16)
tensor, tensor.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int16, numpy=
 array([[[23, 24, 25],
         [12, 13, 14]],
 
        [[15, 16, 17],
         [18, 19, 20]],
 
        [[21, 22, 27],
         [30, 31, 32]]], dtype=int16)>, 3)

### Let's Create random matrices with tf.constant

In [9]:
# Create a random tensor using tf.random with seed
matrix_1 = tf.random.Generator.from_seed(1)
matrix_1 = matrix_1.normal(shape = (3,2,3))
matrix_1, matrix_1.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[ 0.43842274, -0.53439844, -0.07710262],
         [ 1.5658046 , -0.1012345 , -0.2744976 ]],
 
        [[ 1.4204658 ,  1.2609464 , -0.43640924],
         [-1.9633987 , -0.06452483, -1.056841  ]],
 
        [[ 1.0019137 ,  0.6735137 ,  0.06987712],
         [-1.4077919 ,  1.0278524 ,  0.27974114]]], dtype=float32)>, 3)

In [10]:
# Creating another matrix usin tf.random with seed
matrix_2 = tf.random.Generator.from_seed(3)
matrix_2 = matrix_2.normal(shape = (3,2,3))
matrix_2, matrix_2.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[-0.43640924, -1.9633987 , -0.06452483],
         [-1.056841  ,  1.0019137 ,  0.6735137 ]],
 
        [[ 0.06987712, -1.4077919 ,  1.0278524 ],
         [ 0.27974114, -0.01347923,  1.845181  ]],
 
        [[ 0.97061104, -1.0242516 , -0.6544423 ],
         [-0.29738766, -1.3240396 ,  0.28785667]]], dtype=float32)>, 3)

In [11]:
# checking that if they are equal
matrix_1 == matrix_2

<tf.Tensor: shape=(3, 2, 3), dtype=bool, numpy=
array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]]])>

In [12]:
tensor_1 = tf.ones(shape= [3])
tensor_1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [13]:
tf.one_hot(tf.cast(tensor_1,dtype = tf.int32), depth = 4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [17]:
tensor_3 = tf.constant([4,2,2])
tensor_3

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2], dtype=int32)>

In [20]:
tf.one_hot(tensor_3, depth = 5)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>