In [1]:
# importing tensorflow as tf
import tensorflow as tf
tf.__version__

'2.8.0'

In [2]:
!nvidia-smi

Wed Feb 16 09:23:43 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P8    35W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
# Importing numpy as np
import numpy as np
x = np.array([10,12,14,16,17])
y = np.array([20,22,24,26,27])
x, y

(array([10, 12, 14, 16, 17]), array([20, 22, 24, 26, 27]))

In [5]:
x = tf.constant(x)
y = tf.constant(y)
x, y

(<tf.Tensor: shape=(5,), dtype=int64, numpy=array([10, 12, 14, 16, 17])>,
 <tf.Tensor: shape=(5,), dtype=int64, numpy=array([20, 22, 24, 26, 27])>)

In [9]:
# Finding the maximum and minimum values in x & y
tf.reduce_max(x),
tf.reduce_min(y)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [54]:
x = tf.cast(x, dtype = tf.float32)
y= tf.cast(y, dtype = tf.float32)

In [71]:
# 1. Create a model
model = tf.keras.Sequential([
                             tf.keras.layers.Dense(100, name = "Input_layer"),
                             #tf.keras.layers.Dense(10),
                             tf.keras.layers.Dense(1, name = "Output_layer"),


], name = "model_1")

# 2. Compile the model
model.compile(loss = tf.keras.losses.mae,
              optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01),
              metrics = ["mae"]
)

In [64]:
# Visualizing the summary
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input_layer (Dense)         (None, 50)                100       
                                                                 
 dense_7 (Dense)             (None, 10)                510       
                                                                 
 Output_layer (Dense)        (None, 1)                 11        
                                                                 
Total params: 621
Trainable params: 621
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# fitting the model
model.fit(tf.expand_dims(x, axis = -1), y, epochs =100)

Epoch 1/100
1/1 [==============================] - 0s 439ms/step - loss: 22.6818 - mae: 22.6818
Epoch 2/100
1/1 [==============================] - 0s 13ms/step - loss: 19.1926 - mae: 19.1926
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 15.6997 - mae: 15.6997
Epoch 4/100
1/1 [==============================] - 0s 9ms/step - loss: 12.1903 - mae: 12.1903
Epoch 5/100
1/1 [==============================] - 0s 11ms/step - loss: 8.6483 - mae: 8.6483
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 5.0520 - mae: 5.0520
Epoch 7/100
1/1 [==============================] - 0s 10ms/step - loss: 1.5484 - mae: 1.5484
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 2.5969 - mae: 2.5969
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 4.7159 - mae: 4.7159
Epoch 10/100
1/1 [==============================] - 0s 15ms/step - loss: 5.8789 - mae: 5.8789
Epoch 11/100
1/1 [==============================] - 0s 9ms/step

In [70]:
model.predict([29])

array([[47.17188]], dtype=float32)

In [62]:
x, y

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([10., 12., 14., 16., 17.], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([20., 22., 24., 26., 27.], dtype=float32)>)

In [63]:
model.predict([29.0])

array([[41.16441]], dtype=float32)